// Theme colors
export const C = {
  yellow: '#FFD700',
  yellowLight: '#FFF8DC',
  yellowHover: '#FFC107',
  dark: '#1a1a2e',
  darkCard: '#16213e',
  darkBg: '#0f0f23',
  bg: '#0f0f23',
  card: '#16213e',
  cardBorder: '#2a2a4a',
  text: '#e0e0e0',
  textMuted: '#a0a0b0',
  textSecondary: '#c0c0d0',
  white: '#ffffff',
  accent: '#ff6b9d',
  accentGreen: '#50fa7b',
  border: '#2a2a4a',
  red: '#ff5555',
  blue: '#6272a4',
  purple: '#bd93f9',
};

// Common styles
export const S = {
  page: { minHeight: '100vh', background: `linear-gradient(135deg, ${C.darkBg} 0%, ${C.dark} 50%, #16213e 100%)`, color: C.text, fontFamily: "'Segoe UI', 'Microsoft YaHei', sans-serif" },
  container: { maxWidth: 1200, margin: '0 auto', padding: '0 20px' },
  card: { background: C.darkCard, borderRadius: 12, padding: 24, marginBottom: 16, border: `1px solid ${C.border}`, transition: 'transform 0.2s, box-shadow 0.2s' },
  cardHover: { transform: 'translateY(-2px)', boxShadow: `0 8px 25px rgba(255,215,0,0.1)` },
  btn: { background: `linear-gradient(135deg, ${C.yellow}, ${C.yellowHover})`, color: C.dark, border: 'none', borderRadius: 8, padding: '10px 24px', fontSize: 14, fontWeight: 600, cursor: 'pointer', transition: 'all 0.2s' },
  btnOutline: { background: 'transparent', color: C.yellow, border: `1px solid ${C.yellow}`, borderRadius: 8, padding: '8px 20px', fontSize: 14, cursor: 'pointer', transition: 'all 0.2s' },
  btnDanger: { background: C.red, color: C.white, border: 'none', borderRadius: 8, padding: '8px 16px', fontSize: 13, cursor: 'pointer' },
  btnSmall: { padding: '6px 14px', fontSize: 12, borderRadius: 6 },
  input: { width: '100%', padding: '10px 14px', borderRadius: 8, border: `1px solid ${C.border}`, background: C.darkBg, color: C.text, fontSize: 14, outline: 'none', boxSizing: 'border-box' },
  textarea: { width: '100%', padding: '10px 14px', borderRadius: 8, border: `1px solid ${C.border}`, background: C.darkBg, color: C.text, fontSize: 14, outline: 'none', minHeight: 100, resize: 'vertical', boxSizing: 'border-box', fontFamily: 'inherit' },
  select: { padding: '10px 14px', borderRadius: 8, border: `1px solid ${C.border}`, background: C.darkBg, color: C.text, fontSize: 14, outline: 'none' },
  label: { display: 'block', marginBottom: 6, fontSize: 13, color: C.textMuted, fontWeight: 500 },
  formGroup: { marginBottom: 16 },
  grid2: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: 20 },
  grid3: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 16 },
  flex: { display: 'flex', alignItems: 'center', gap: 12 },
  flexBetween: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  tag: { display: 'inline-block', padding: '3px 10px', borderRadius: 20, fontSize: 12, fontWeight: 500 },
  badge: { background: C.red, color: C.white, borderRadius: '50%', width: 18, height: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 700 },
  avatar: { width: 40, height: 40, borderRadius: '50%', objectFit: 'cover', background: C.border },
  divider: { height: 1, background: C.border, margin: '20px 0' },
  score: { color: C.yellow, fontSize: 24, fontWeight: 700 },
  modal: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modalContent: { background: C.darkCard, borderRadius: 16, padding: 32, maxWidth: 500, width: '90%', maxHeight: '80vh', overflowY: 'auto', border: `1px solid ${C.border}` },
  tab: (active) => ({ padding: '10px 20px', cursor: 'pointer', borderBottom: active ? `3px solid ${C.yellow}` : '3px solid transparent', color: active ? C.yellow : C.textMuted, fontWeight: active ? 600 : 400, transition: 'all 0.2s', background: 'none', border: 'none', fontSize: 15 }),
  starBtn: (filled) => ({ background: 'none', border: 'none', cursor: 'pointer', fontSize: 22, color: filled ? C.yellow : C.border, transition: 'color 0.15s', padding: 2 }),
  likeBtn: (liked) => ({ background: 'none', border: 'none', cursor: 'pointer', color: liked ? C.accent : C.textMuted, display: 'flex', alignItems: 'center', gap: 4, fontSize: 13, transition: 'color 0.2s', padding: '4px 8px', borderRadius: 6 }),
};
